name = "stm32_graphics"
description = "Graphics for STM32"
version = "1.0.0"
licenses = "BSD-3-Clause"

tags = ["embedded"]
website = "https://github.com/ohenley/stm32_graphics"

authors = ["AdaCore"]
maintainers = ["olivier henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[[depends-on]]
stm32_config = "1.0.0"
beta_types = "1.0.0"
gnat_arm_elf = "^12"
hal_embedded = "1.0.0"
stm32_drivers = "1.0.0"
stm32_boards = "1.0.0"
